version: '3'
services:
  db:
    image: couchdb:1.6.1
    container_name: drunken-master-db
    ports:
    - "5984:5984"
    volumes:
    - db-data:/usr/local/var/lib/couchdb
  web:
    build: .
    env_file: ./.docker/.env
    container_name: drunken-master
    ports:
    - "9999:9999"
    links:
    - db
volumes:
  db-data: